### ISSUE TITLE
gives error when trying to change quality

### ISSUE THREAD

**Issue by turgutcecen** [awekrx/AFK-Twitch-drops#1]
thanks it works but during quality change it gives this error and closes

```
AFK-Twitch-drops\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'click')
    at __puppeteer_evaluation_script__:2:55
    at ExecutionContext._evaluateInternal (C:\Users\Administrator\Desktop\twitch\AFK-Twitch-drops\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Desktop\twitch\AFK-Twitch-drops\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async changeQuality (C:\Users\Administrator\Desktop\twitch\AFK-Twitch-drops\index.js:192:5)
    at async main (C:\Users\Administrator\Desktop\twitch\AFK-Twitch-drops\index.js:273:13)
```

**Comment by awekrx** [comment]
> thanks it works but during quality change it gives this error and closes
> 
> ```
> AFK-Twitch-drops\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
>             throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
>                   ^
> 
> Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'click')
>     at __puppeteer_evaluation_script__:2:55
>     at ExecutionContext._evaluateInternal (C:\Users\Administrator\Desktop\twitch\AFK-Twitch-drops\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ExecutionContext.evaluate (C:\Users\Administrator\Desktop\twitch\AFK-Twitch-drops\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
>     at async changeQuality (C:\Users\Administrator\Desktop\twitch\AFK-Twitch-drops\index.js:192:5)
>     at async main (C:\Users\Administrator\Desktop\twitch\AFK-Twitch-drops\index.js:273:13)
> ```

I did not find such a bug, but added ignoring the quality change when it can occur
